# Generated by Django 5.0.7 on 2024-07-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_client_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_booking',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
